In [1]:
import numpy as np
import pandas as pd

In [7]:
#Mode in categorical + Ordinal data
#Mean when there are no outliers
#Median when there are outliers present

#when less missing values -> fill
#when more missing values -> drop

In [8]:
#head,tail,info,describe,duplicated,.sum,fill and drop of missing values

In [24]:
#DATA CLEANING :
df = pd.read_csv("hotel_booking.csv")
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [25]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [26]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

In [28]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [30]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
dtype: int64

In [34]:
df.fillna(0)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [37]:
df.dropna()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
2392,Resort Hotel,0,6,2015,October,42,11,2,0,2,...,Transient,82.0,1,1,Check-Out,2015-10-13,Darryl Phillips,Darryl_Phillips@hotmail.com,731-360-4698,************2677
2697,Resort Hotel,0,24,2015,October,44,26,7,15,1,...,Transient-Party,52.2,0,0,Check-Out,2015-11-17,Lynn Gaines,Lynn.Gaines77@yahoo.com,866-053-4253,************6564
2867,Resort Hotel,0,24,2015,November,45,3,0,3,2,...,Transient-Party,48.0,0,0,Check-Out,2015-11-06,Richard Diaz,Richard.Diaz@mail.com,836-443-4157,************8259
2877,Resort Hotel,0,24,2015,November,45,3,2,10,1,...,Transient-Party,40.0,0,0,Check-Out,2015-11-15,Karen Lynch,KarenLynch@att.com,153-365-6906,************5124
2878,Resort Hotel,0,24,2015,November,45,3,3,10,2,...,Transient-Party,48.0,0,0,Check-Out,2015-11-16,Joseph Livingston,Joseph.L@protonmail.com,175-653-7050,************3824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112499,City Hotel,0,13,2017,May,21,24,0,1,2,...,Transient-Party,150.0,0,1,Check-Out,2017-05-25,Meghan Flores,Flores_Meghan@verizon.com,439-451-4147,************8201
113046,City Hotel,0,13,2017,May,22,29,1,3,1,...,Transient,95.0,0,0,Check-Out,2017-06-02,Jordan Olson,Jordan.O@mail.com,860-873-3107,************9138
113082,City Hotel,0,13,2017,May,22,29,1,3,2,...,Transient,110.0,0,0,Check-Out,2017-06-02,Robert Reynolds,Robert.R@yandex.com,604-257-1344,************8808
113627,City Hotel,0,210,2017,June,23,9,0,1,2,...,Transient,135.0,0,0,Check-Out,2017-06-10,Mrs. Colleen Mcdaniel MD,Mrs._MD@outlook.com,929-209-4199,************4558
116451,City Hotel,0,191,2017,July,29,16,2,2,2,...,Transient,120.6,0,2,Check-Out,2017-07-20,Jeffrey Lane,Lane.Jeffrey14@verizon.com,616-943-4805,************3172

In [38]:
df = df.head(50)

In [39]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,Jasmine Fletcher,JFletcher43@xfinity.com,190-271-6743,************9263
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,Transient,107.00,0,0,Check-Out,2015-07-03,Dylan Rangel,Rangel.Dylan@comcast.net,420-332-5209,************6994
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,Transient,103.00,0,1,Check-Out,2015-07-03,William Velez,Velez_William@mail.com,286-669-4333,************8729
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,Transient,82.00,0,1,Canceled,2015-05-06,Steven Murphy,Steven.Murphy54@aol.com,341-726-5787,************3639
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,Transient,105.50,0,0,Canceled,2015-04-22,Michael Moore,MichaelMoore81@outlook.com,316-648-6176,************9190
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,Transient,123.00,0,0,Canceled,2015-06-23,Priscilla Collins PhD,PhD.Priscilla74@att.com,833-887-7898,************4642
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,Transient,145.00,0,0,Check-Out,2015-07-05,Laurie Smith,Smith.Laurie@att.com,804-383-4080,************5450
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,Transient,97.00,0,3,Check-Out,2015-07-05,Casey Thomas,Casey_T78@outlook.com,211-071-2173,************8518
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,Transient,154.77,0,1,Check-Out,2015-07-05,Rachel Friedman,Rachel.F@protonmail.com,435-075-8409,************9767
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,Transient,94.71,0,0,Check-Out,2015-07-05,Edward Torres,Edward.T@zoho.com,790-746-7471,************7719
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,Transient,97.00,0,3,Check-Out,2015-07-05,Samuel Zavala,Zavala_Samuel46@xfinity.com,649-384-5387,************7612
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,Contract,97.50,0,0,Check-Out,2015-07-05,Dr. Victor Martin,Dr.Martin@xfinity.com,331-430-8824,************6279
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,Transient,88.20,0,0,Check-Out,2015-07-02,Sara Lee,Sara.L@hotmail.com,573-306-9938,************8950
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,Transient,107.42,0,0,Check-Out,2015-07-02,Curtis Rodriguez,CRodriguez@verizon.com,466-424-2102,************1179
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,Transient,153.00,0,1,Check-Out,2015-07-05,Stephanie Schmidt,StephanieSchmidt@hotmail.com,896-642-1049,************1110
20,Resort Hotel,0,37,2015,July,27,1,1,4,1,...,Transient,97.29,0,1,Check-Out,2015-07-06,John Matthews,John.Matthews@aol.com,952-496-4398,************1019
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,Transient,84.67,0,1,Check-Out,2015-07-07,Robert Chung,Robert.Chung47@yandex.com,382-465-6552,************8524
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,Transient,84.67,0,1,Check-Out,2015-07-07,Mark Garcia,MGarcia16@comcast.net,784-675-4921,************4371
23,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,Transient,99.67,0,1,Check-Out,2015-07-07,Brandon Taylor,BrandonTaylor@hotmail.com,227-329-7167,************8470
24,Resort Hotel,0,127,2015,July,27,1,2,5,2,...,Contract,94.95,0,1,Check-Out,2015-07-01,Angie Sanchez,Angie_Sanchez@att.com,211-889-2476,************8871
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,Transient,63.60,1,0,Check-Out,2015-07-08,Alexis King,King_Alexis70@hotmail.com,103-516-5853,************6809
26,Resort Hotel,0,48,2015,July,27,1,2,5,2,...,Contract,79.50,0,0,Check-Out,2015-07-08,Michael Davidson,MichaelDavidson82@att.com,336-525-2460,************8662
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,Transient,107.00,0,2,Canceled,2015-05-11,Jaime Flynn,JaimeFlynn29@gmail.com,549-866-3721,************9660
28,Resort Hotel,0,77,2015,July,27,1,2,5,2,...,Transient,94.00,0,0,Check-Out,2015-07-08,Mrs. Alicia Williams,Mrs..W61@yandex.com,427-564-4927,************4445
29,Resort Hotel,0,99,2015,July,27,1,2,5,2,...,Transient,87.30,1,1,Check-Out,2015-07-08,Heather Hart,Heather.H@xfinity.com,431-329-6663,************2780
30,Resort Hotel,0,118,2015,July,27,1,4,10,1,...,Transient,62.00,0,2,Check-Out,2015-07-15,Diamond Wilson,Wilson.Diamond@comcast.net,870-563-6202,************8017
31,Resort Hotel,0,95,2015,July,27,1,4,11,2,...,Transient,63.86,0,0,Check-Out,2015-07-16,Paul Williams,Williams_Paul@xfinity.com,789-736-8837,************7006
32,Resort Hotel,1,96,2015,July,27,1,2,8,2,...,Transient,108.30,0,2,Canceled,2015-05-29,Reginald Cunningham,Reginald_C57@outlook.com,800-249-2144,************5699
33,Resort Hotel,0,69,2015,July,27,2,2,4,2,...,Transient,65.50,0,0,Check-Out,2015-07-08,Willie Sims,Willie_S@yahoo.com,790-830-7635,************7682
34,Resort Hotel,1,45,2015,July,27,2,1,3,3,...,Transient,108.80,0,1,Canceled,2015-05-19,Alex Brown,Alex.B@zoho.com,956-737-1944,************4084
35,Resort Hotel,1,40,2015,July,27,2,1,3,3,...,Transient,108.80,0,1,Canceled,2015-06-19,Virginia Holden,Virginia.H@aol.com,734-480-9929,************8469
36,Resort Hotel,0,15,2015,July,27,2,1,3,2,...,Transient,98.00,0,0,Check-Out,2015-07-06,John Smith,John_Smith@xfinity.com,624-965-3392,************6445
37,Resort Hotel,0,36,2015,July,27,2,1,3,3,...,Transient,108.80,0,1,Check-Out,2015-07-06,Jennifer Barton,JBarton@hotmail.com,902-792-8048,************2544
38,Resort Hotel,1,43,2015,July,27,2,1,3,3,...,Transient,108.80,0,0,Canceled,2015-05-23,Richard Holt,Richard.Holt@hotmail.com,517-420-6344,************7544
39,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,Transient,137.00,0,1,Check-Out,2015-07-07,Amy Green,Amy.Green56@gmail.com,858-208-4589,************3073
40,Resort Hotel,1,45,2015,July,27,2,2,3,2,...,Transient,117.81,0,0,Canceled,2015-05-18,Kimberly Perez,Perez.Kimberly84@hotmail.com,320-615-3590,************4653
41,Resort Hotel,0,45,2015,July,27,2,2,3,2,...,Contract,79.50,0,0,Check-Out,2015-07-07,Carly Armstrong,CArmstrong@mail.com,521-784-3601,************7391
42,Resort Hotel,0,16,2015,July,27,2,2,3,2,...,Transient,123.00,0,0,Check-Out,2015-07-07,Scott Hammond,ScottHammond41@verizon.com,632-108-8350,************4823
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,Transient,137.00,0,1,Check-Out,2015-07-07,Debra Fuller,Debra.Fuller@protonmail.com,229-134-3710,************3550
44,Resort Hotel,0,107,2015,July,27,2,2,5,2,...,Transient,110.70,0,2,Check-Out,2015-07-09,Rachel Davis,RachelDavis@mail.com,549-261-2558,************2810
45,Resort Hotel,1,47,2015,July,27,2,2,5,2,...,Transient,153.00,0,0,Canceled,2015-06-02,Michael Mccormick,Mccormick.Michael19@aol.com,380-830-9585,************2950
46,Resort Hotel,0,96,2015,July,27,2,2,5,2,...,Transient,58.95,0,1,Check-Out,2015-07-09,Ann Sullivan,AnnSullivan@att.com,947-577-3720,************4782
47,Resort Hotel,0,113,2015,July,27,2,2,5,2,...,Transient-Party,82.88,0,2,Check-Out,2015-07-09,Rachel Wallace,Rachel_W79@xfinity.com,870-988-2775,************1133
48,Resort Hotel,0,90,2015,July,27,2,2,5,2,...,Contract,82.35,0,0,Check-Out,2015-07-09,Carla Ferguson,Carla_Ferguson@att.com,724-910-8709,************8339
49,Resort Hotel,0,50,2015,July,27,2,2,5,2,...,Transient,119.35,0,1,Check-Out,2015-07-09,Greg Hardin,Hardin_Greg@gmail.com,488-646-3204,************1449

In [40]:
df.isna().sum()

hotel                              0
is_canceled                        0
lead_time                          0
arrival_date_year                  0
arrival_date_month                 0
arrival_date_week_number           0
arrival_date_day_of_month          0
stays_in_weekend_nights            0
stays_in_week_nights               0
adults                             0
children                           0
babies                             0
meal                               0
country                            1
market_segment                     0
distribution_channel               0
is_repeated_guest                  0
previous_cancellations             0
previous_bookings_not_canceled     0
reserved_room_type                 0
assigned_room_type                 0
booking_changes                    0
deposit_type                       0
agent                              8
company                           49
days_in_waiting_list               0
customer_type                      0
adr                                0
required_car_parking_spaces        0
total_of_special_requests          0
reservation_status                 0
reservation_status_date            0
name                               0
email                              0
phone-number                       0
credit_card                        0
dtype: int64

In [46]:
df.fillna(df.mean(numeric_only = True))['company']

0     110.0
1     110.0
2     110.0
3     110.0
4     110.0
5     110.0
6     110.0
7     110.0
8     110.0
9     110.0
10    110.0
11    110.0
12    110.0
13    110.0
14    110.0
15    110.0
16    110.0
17    110.0
18    110.0
19    110.0
20    110.0
21    110.0
22    110.0
23    110.0
24    110.0
25    110.0
26    110.0
27    110.0
28    110.0
29    110.0
30    110.0
31    110.0
32    110.0
33    110.0
34    110.0
35    110.0
36    110.0
37    110.0
38    110.0
39    110.0
40    110.0
41    110.0
42    110.0
43    110.0
44    110.0
45    110.0
46    110.0
47    110.0
48    110.0
49    110.0
Name: company, dtype: float64

In [51]:
categorical_columns = df.select_dtypes(include=['object', 'category']).columns
print(categorical_columns)
print("Total categorical columns:", len(categorical_columns))

Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type', 'reservation_status',
       'reservation_status_date', 'name', 'email', 'phone-number',
       'credit_card'],
      dtype='object')
Total categorical columns: 16

In [52]:
numerical_columns = df.select_dtypes(include=['number']).columns
print(numerical_columns)
print("Total numerical columns:", len(numerical_columns))

#no ordinal column in this data set

Index(['is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_week_number', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests'],
      dtype='object')
Total numerical columns: 20

In [55]:
#uplodaing and saving : 
#csv,excel,html,json
#excel,csv,sql,json

In [58]:
#CLUSTERED BAR CHART : COMPARISON
#WATERFALL CHART : VARIANCE COMPARISON
#GAUGE CHART : KEY PERFORMANCE INTERFACE (SINGLE VALUE NUMERICAL)
#PIE CHART : PROPORTION SMALL CATEGORIES
#DONUT CHART : PROPRTION SEGMENTS 
#AREA CHART : VOLUME AND TREND ANALYSIS
#CARD : PLACE NEAR TITLE SINGLE KPI(ONLY NUMERICAL DATA)
#SLICER : CONNECTING ALL THE CHART IN THE DASHBOARD AND MAKING DASHBOARD INTERACTIVE